def excited_state(mybasis,myfile,function,w=0,epsilon=0):
    openfile=myfile+'.ts'
    myco=myfile+'.xyz'
    ts_file=open(openfile, 'w')
    ts_file.write('method   '+function)
    ts_file.write('\n')
    ts_file.write('basis  '+mybasis)
    ts_file.write('\n')
    if w!=0:
        ts_file.write('rc_w  '+str(w))
        ts_file.write('\n')
    ts_file.write('pcm cosmo')
    ts_file.write('\n')
    ts_file.write('epsilon 2.38')
    ts_file.write('\n')
    ts_file.write('max_l_in_basis 2 # neglects any function higher than d')
    ts_file.write('\n')
    ts_file.write('sphericalbasis yes # switch on spherical basis representation')
    ts_file.write('\n')
    ts_file.write('guess sad')
    ts_file.write('\n')
    ts_file.write('precision double')
    ts_file.write('\n')
    ts_file.write('dftgrid 3')
    ts_file.write('\n')
    ts_file.write('threall 1.0e-14')
    ts_file.write('\n')
    ts_file.write('threspdp 1.0e-4')
    ts_file.write('\n')
    ts_file.write('convthre 1.0e-6')
    ts_file.write('\n')
    ts_file.write('xtol 1.0e-6')
    ts_file.write('\n')
    ts_file.write('coordinates '+myco)
    ts_file.write('\n')
    ts_file.write('hhtda yes')
    ts_file.write('\n')
    ts_file.write('cisnumstates 7')
    ts_file.write('\n')
    ts_file.write('hhtdasinglets 4')
    ts_file.write('\n')
    ts_file.write('hhtdatriplets 3')
    ts_file.write('\n')
    ts_file.write('cisalgorithm davidson')
    ts_file.write('\n')
    ts_file.write('cisguessvecs 9')
    ts_file.write('\n')
    ts_file.write('cismax 100')
    ts_file.write('\n')
    ts_file.write('cismaxiter 1000')
    ts_file.write('\n')
    ts_file.write('cistarget 1')
    ts_file.write('\n')
    ts_file.write('cisconvtol 1.0e-6')
    ts_file.write('\n')
    ts_file.write('cphftol 1.0e-6')
    ts_file.write('\n')
    ts_file.write('cphfiter 500')
    ts_file.write('\n')
    ts_file.write('charge -2')
    ts_file.write('\n')
    ts_file.write('spinmult 1')
    ts_file.write('\n')
    ts_file.write('run energy')
    ts_file.write('\n')
    ts_file.close()
